version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: carbon-credit-db
    environment:
      POSTGRES_DB: carbon_credit_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - carbon-credit-network

  app:
    build: .
    container_name: carbon-credit-app
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: password
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/carbon_credit_db
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - carbon-credit-network

volumes:
  postgres_data:

networks:
  carbon-credit-network:
    driver: bridge
